
export const getModalElements = () => ({
    // Cabecera
    nombre: document.getElementById("modal-nombre"),
    cargo: document.getElementById("modal-cargo"),
    codigo: document.getElementById("modal-codigo"),
    cedula: document.getElementById("modal-cedula"),
    edad: document.getElementById("modal-edad"),
    ingreso: document.getElementById("modal-ingreso"),
    antiguedad: document.getElementById("modal-antiguedad"),
    estado: document.getElementById("modal-estado"),
    zona: document.getElementById("modal-zona"),
    padrino: document.getElementById("modal-padrino"),
    img: document.getElementById("modal-img") as HTMLImageElement,
    imageModal: document.getElementById("image-zoom-modal"),
    zoomedImage: document.getElementById("zoomed-image") as HTMLImageElement,
    closeImageZoom: document.getElementById("close-image-zoom"),
    efMensual: document.getElementById("modal-ef-mensual"),
    efMensualLabel: document.getElementById("modal-ef-mensual-label"),
    efMensualStatus: document.getElementById("modal-ef-mensual-status"),
    efAnual: document.getElementById("modal-ef-anual"),
    statusIndicator: document.getElementById("modal-status-indicator"),
    statusText: document.getElementById("modal-status-text"),

    // Filtros y Tablas
    selects: document.querySelectorAll(".modal-year-select"),
    monthSelect: document.getElementById("modal-month-select") as HTMLSelectElement,
    monthSelects: document.querySelectorAll(".modal-month-select"),
    kmTitle: document.getElementById("modal-km-table-title"),
    kmRendimientoTitle: document.getElementById("km-rendimiento-title"),
    btnKmGlobal: document.getElementById("btn-km-global") as HTMLButtonElement,
    kmBody: document.getElementById("modal-km-table-body"),
    novBody: document.getElementById("modal-nov-matrix-body"),
    novBadge: document.getElementById("modal-nov-tipos-badge"),

    // KPIs
    bonosVal: document.getElementById("modal-kpi-bonos-val"),
    kmVal: document.getElementById("modal-kpi-km-val"),
    catVal: document.getElementById("modal-kpi-categoria"),
    kmProgVal: document.getElementById("modal-km-prog-val"),
    kmEjecVal: document.getElementById("modal-km-ejec-val"),
    kmEffVal: document.getElementById("modal-km-eff-val"),
    kmProgBar: document.getElementById("modal-km-prog-bar"),
    kmEjecBar: document.getElementById("modal-km-ejec-bar"),
    kmEffBar: document.getElementById("modal-km-eff-bar"),
    kmEffStatus: document.getElementById("modal-km-eff-status"),
    bonoBase: document.getElementById("modal-bono-base"),
    bonoDed: document.getElementById("modal-bono-deduccion"),
    bonoDesc: document.getElementById("modal-bono-descuento"),
    bonoFin: document.getElementById("modal-bono-final"),

    // Novedades IDs específicos
    novTotal: document.getElementById("modal-nov-total"),
    novAnios: document.getElementById("modal-nov-anios"),
    novTipos: document.getElementById("modal-nov-tipos"),
    novPromo: document.getElementById("modal-nov-promo"),
    novDistGrid: document.getElementById("modal-nov-dist-grid"),
    novTableHeader: document.getElementById("modal-nov-table-header"),
    dedBody: document.getElementById("modal-deducciones-body"),
    dedTitle: document.getElementById("modal-deducciones-title"),
});
